apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: 'number_of_tasks{}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name: 
        as: number_of_tasks
      metricsQuery: '<<.Series>>{<<.LabelMatchers>>}'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-adapter
  namespace: prometheus-resources