---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa-demo
  labels:
    name: hpa-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-task-demo
  namespace: hpa-demo
  labels:
    app: custom-metrics-task-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-task-demo
  template:
    metadata:
      labels:
        app: custom-metrics-task-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: custom-metrics-task-demo
          image: ilyamochalov/k8s-autoscaling-custom-metrics-task-demo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 1
              memory: 500Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-task-demo
  namespace: hpa-demo
spec:
  selector:
    app: custom-metrics-task-demo
  ports:
    - name: http
      protocol: TCP
      port: 5050