
---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa-demo
  labels:
    name: hpa-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-demo
  namespace: hpa-demo
  labels:
    app: cpu-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-demo
  template:
    metadata:
      labels:
        app: cpu-demo
    spec:
      containers:
        - name: cpu-demo
          image: ilyamochalov/k8s-autoscaling-cpu-demo:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 1
              memory: 500Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-demo
  namespace: hpa-demo
spec:
  selector:
    app: cpu-demo
  ports:
    - name: http
      protocol: TCP
      port: 5000


